### PR TITLE
Update old-resource maintainers

### PR DESCRIPTION
**Pull request by thers**

### CODE REVIEW

**Comment by thers** [comment]
<details>
<summary>Details of PR</summary>
<strong>Resource name</strong>: old-resource<br/>
<strong>Metainfo.v1</strong>: <pre>{"version":"1","is_new_resource":false,"is_deleted_resource":false,"resource_maintainers":["thers","thers-throwaway"],"previous_resource_maintainers":["thers-throwaway"],"resource_name":"old-resource","files":[],"last_commit_hash":"2925ba9aacc571964d7e676fd55bcbe54c4807cc"}</pre><br/>
</details>

**Comment by thers** [comment]
Moderators review required due to:
- Resource maintainers will be altered


Maintainers review required due to:
- Resource has multiple maintainers, consensus required

**Comment by thers** [comment]
PR will be merged in 2 hours.

**Comment by thers** [comment]
<details>
<summary>Details of PR</summary>
<strong>Resource name</strong>: old-resource<br/>
<strong>Metainfo.v1</strong>: <pre>{"version":"1","is_new_resource":false,"is_deleted_resource":false,"resource_maintainers":["thers","thers-throwaway"],"previous_resource_maintainers":["thers-throwaway"],"resource_name":"old-resource","files":[],"last_commit_hash":"2925ba9aacc571964d7e676fd55bcbe54c4807cc"}</pre><br/>
</details>

**Comment by thers** [comment]
Moderators review required due to:
- Resource maintainers will be altered

**Comment by thers** [comment]
PR will be merged in 2 hours.

**Review by cerium-cfx — APPROVED** [review]
sux but k.

**Comment by thers** [comment]
PR will be merged in 2 hours.

**Comment by thers** [comment]
@thers /merge

**Comment by blattersturm** [comment]
comment

**Pull request merged**
