### PR TITLE
Old review from authors

### PR DESCRIPTION
**Pull request by thers**

### CODE REVIEW

**Comment by thers** [comment]
<details>
<summary>Details of PR</summary>
**Resource name**: old-resource
**Metainfo**: {"is_new_resource":false,"is_deleted_resource":false,"resource_maintainers":["thers-throwaway"],"previous_resource_maintainers":["thers-throwaway"],"resource_name":"old-resource","files":[{"name":"old-resource/client.lua","size":17,"is_binary":true}]}
</details>

**Comment by thers** [comment]
<details>
<summary>Details of PR</summary>
<strong>Resource name</strong>: old-resource
<strong>Metainfo</strong>: <pre>{"is_new_resource":false,"is_deleted_resource":false,"resource_maintainers":["thers-throwaway"],"previous_resource_maintainers":["thers-throwaway"],"resource_name":"old-resource","files":[{"name":"old-resource/client.lua","size":17,"is_binary":true}]}</pre>
</details>

**Comment by thers** [comment]
<details>
<summary>Details of PR</summary>
<strong>Resource name</strong>: old-resource<br/>
<strong>Metainfo</strong>: <pre>{"is_new_resource":false,"is_deleted_resource":false,"resource_maintainers":["thers-throwaway"],"previous_resource_maintainers":["thers-throwaway"],"resource_name":"old-resource","files":[{"name":"old-resource/client.lua","size":17,"is_binary":true}]}</pre><br/>
</details>

**Comment by thers** [comment]
<details>
<summary>Details of PR</summary>
<strong>Resource name</strong>: old-resource<br/>
<strong>Metainfo.v1</strong>: <pre>{"version":"1","is_new_resource":false,"is_deleted_resource":false,"resource_maintainers":["thers-throwaway"],"previous_resource_maintainers":["thers-throwaway"],"resource_name":"old-resource","files":[{"name":"old-resource/client.lua","size":17,"is_binary":true}],"last_commit_hash":"dbda4188bd2457d02c67b12814a456dea9aeff36"}</pre><br/>
</details>

**Comment by thers** [comment]
<details>
<summary>Details of PR</summary>
<strong>Resource name</strong>: old-resource<br/>
<strong>Metainfo.v1</strong>: <pre>{"version":"1","is_new_resource":false,"is_deleted_resource":false,"resource_maintainers":["thers-throwaway"],"previous_resource_maintainers":["thers-throwaway"],"resource_name":"old-resource","files":[{"name":"old-resource/client.lua","size":17,"is_binary":true}],"last_commit_hash":"dbda4188bd2457d02c67b12814a456dea9aeff36"}</pre><br/>
</details>

**Comment by thers** [comment]
<details>
<summary>Details of PR</summary>
<strong>Resource name</strong>: old-resource<br/>
<strong>Metainfo.v1</strong>: <pre>{"version":"1","is_new_resource":false,"is_deleted_resource":false,"resource_maintainers":["thers-throwaway"],"previous_resource_maintainers":["thers-throwaway"],"resource_name":"old-resource","files":[{"name":"old-resource/client.lua","size":17,"is_binary":false}],"last_commit_hash":"dbda4188bd2457d02c67b12814a456dea9aeff36"}</pre><br/>
</details>

**Review by thers-throwaway — APPROVED** [review]

**Comment by thers** [comment]
Maintainers review required due to:
- PR author is not a maintainer

**Comment by thers** [comment]
Maintainers review required due to:
- PR author is not a maintainer

**Comment by thers** [comment]
<details>
<summary>Details of PR</summary>
<strong>Resource name</strong>: old-resource<br/>
<strong>Metainfo.v1</strong>: <pre>{"version":"1","is_new_resource":false,"is_deleted_resource":false,"resource_maintainers":["thers-throwaway"],"previous_resource_maintainers":["thers-throwaway"],"resource_name":"old-resource","files":[{"name":"old-resource/client.lua","size":17,"is_binary":false}],"last_commit_hash":"dbda4188bd2457d02c67b12814a456dea9aeff36"}</pre><br/>
</details>

**Comment by thers** [comment]
Maintainers review required due to:
- PR author is not a maintainer

**Comment by thers** [comment]
Maintainers review required due to:
- PR author is not a maintainer

**Comment by thers** [comment]
Maintainers review required due to:
- PR author is not a maintainer of target resource

**Comment by thers** [comment]
PR will be merged in 2 hours.

**Pull request merged**
