### PR TITLE
Delete me from old-resource maintainers

### PR DESCRIPTION
**Pull request by thers**

### CODE REVIEW

**Comment by thers** [comment]
<details>
<summary>Details of PR</summary>
<strong>Resource name</strong>: old-resource<br/>
<strong>Metainfo.v1</strong>: <pre>{"version":"1","is_new_resource":false,"is_deleted_resource":false,"resource_maintainers":["thers-throwaway"],"previous_resource_maintainers":["thers","thers-throwaway"],"resource_name":"old-resource","files":[],"last_commit_hash":"e49849c7d57342476af6bc80464297415f58c3b7"}</pre><br/>
</details>

**Comment by thers** [comment]
<details>
<summary>Details of PR</summary>
<strong>Resource name</strong>: old-resource<br/>
<strong>Metainfo.v1</strong>: <pre>{"version":"1","is_new_resource":false,"is_deleted_resource":false,"resource_maintainers":["thers-throwaway"],"previous_resource_maintainers":["thers","thers-throwaway"],"resource_name":"old-resource","files":[],"last_commit_hash":"e49849c7d57342476af6bc80464297415f58c3b7"}</pre><br/>
</details>

**Comment by thers** [comment]
Moderators review required due to:
- Resource maintainers will be altered


Maintainers review required due to:
- Resource has multiple maintainers, consensus required

**Comment by thers** [comment]
Moderators review required due to:
- Resource maintainers will be altered


Maintainers review required due to:
- Resource has multiple maintainers, consensus required



<details>
<summary>Details of PR</summary>
<strong>Resource name</strong>: old-resource<br/>
<strong>Metainfo.v1</strong>: <pre>{"version":"1","is_new_resource":false,"is_deleted_resource":false,"resource_maintainers":["thers-throwaway"],"previous_resource_maintainers":["thers","thers-throwaway"],"resource_name":"old-resource","files":[],"last_commit_hash":"e49849c7d57342476af6bc80464297415f58c3b7"}</pre><br/>
</details>

**Comment by thers** [comment]
**Moderators** review required due to:
- Resource maintainers will be altered


**Maintainers** review required due to:
- Resource has multiple maintainers, consensus required


<hr/>
<details>
<summary>Details of PR</summary>
<strong>Resource name</strong>: old-resource<br/>
<strong>Metainfo.v1</strong>: <pre>{"version":"1","is_new_resource":false,"is_deleted_resource":false,"resource_maintainers":["thers-throwaway"],"previous_resource_maintainers":["thers","thers-throwaway"],"resource_name":"old-resource","files":[],"last_commit_hash":"e49849c7d57342476af6bc80464297415f58c3b7"}</pre><br/>
</details>

**Comment by thers** [comment]
**Moderators** review required due to:
- Resource maintainers will be altered


**Maintainers** review required due to:
- Resource has multiple maintainers


<hr/>
<details>
<summary>Details of PR</summary>
<strong>Resource name</strong>: old-resource<br/>
<strong>Metainfo.v1</strong>: <pre>{"version":"1","is_new_resource":false,"is_deleted_resource":false,"resource_maintainers":["thers-throwaway"],"previous_resource_maintainers":["thers","thers-throwaway"],"resource_name":"old-resource","files":[],"last_commit_hash":"e49849c7d57342476af6bc80464297415f58c3b7"}</pre><br/>
</details>

**Review by thers-throwaway — APPROVED** [review]

**Comment by thers** [comment]
PR will be merged in 2 hours.

**Pull request merged**
